version: '3.9'

services:
  app:
    build: .
    container_name: ecommerce_app
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/ecommerce
      - INVENTORY_API_URL=https://fakestoreapi.com/products
      - SECRET_KEY=supersecreto
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=order_queue
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
